### ISSUE TITLE
Is reloaded.repl a good usage of code?

### ISSUE THREAD

**Issue by SevereOverfl0w** [danielsz/system-advanced-example#1]
https://github.com/danielsz/system-advanced-example/blob/master/src/example/handler.clj#L21

I'm not sure if this is a great example of how to pull a dependency out of the current system map from a route handler. I've no idea what the correct way to do it is, but I'm not sure if using reloaded.repl's global is a great idea in this case.

**Comment by danielsz** [comment]
This is being addressed in https://github.com/danielsz/system-dependency-injection/blob/master/src/example/handler.clj

Global map vs dependency injection is discussed in the README. 
https://github.com/danielsz/system#at-runtime-global-system-map-vs-dependency-injection

**Comment by SevereOverfl0w** [comment]
Ah, okay. Hadn't thought to check the readme of system for a discussion of these things, thanks!
